version: '3'

services:

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=safecho

  redis:
    image: redis:alpine

  celery:
    environment:
      - C_FORCE_ROOT=true
    build: .
    command: celery -A Project  worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  web:
    build: .
    stdin_open: true
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
volumes:
  postgres_data:

